name: Merge OSINT JSON Files

on:
  push:
    paths:
      - 'resources/osint/*.json'
    branches:
      - main
      - osint-sources
  pull_request:
    paths:
      - 'resources/osint/*.json'
    branches:
      - main
      - osint-sources

jobs:
  merge_osint_json_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Merge OSINT JSON Files
        run: |
          python resources/osint/osint_merge.py

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Add and commit changes
        run: |
          git add resources/osint/*.json
          git commit -m "Auto-merged OSINT JSON files" || exit 0
      - name: Push changes
        run: |
          git push origin HEAD:main>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
